debug: "invalid IP" in output
```
compose-e2e-dotenv-profiles-regular-service-1    nginx:alpine   "/docker-entrypoint.…"   regular-service    Less than a second ago   Up Less than a second   80/tcp
    ps_test.go:97:
        	Error Trace:	/home/runner/work/compose/compose/pkg/e2e/ps_test.go:97
        	Error:      	Not equal:
        	            	expected: api.PortPublishers{api.PortPublisher{URL:"", TargetPort:80, PublishedPort:0, Protocol:"tcp"}, api.PortPublisher{URL:"", TargetPort:443, PublishedPort:0, Protocol:"tcp"}, api.PortPublisher{URL:"", TargetPort:8080, PublishedPort:0, Protocol:"tcp"}}
        	            	actual  : api.PortPublishers{api.PortPublisher{URL:"invalid IP", TargetPort:80, PublishedPort:0, Protocol:"tcp"}, api.PortPublisher{URL:"invalid IP", TargetPort:443, PublishedPort:0, Protocol:"tcp"}, api.PortPublisher{URL:"invalid IP", TargetPort:8080, PublishedPort:0, Protocol:"tcp"}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,3 +2,3 @@
        	            	  (api.PortPublisher) {
        	            	-  URL: (string) "",
        	            	+  URL: (string) (len=10) "invalid IP",
        	            	   TargetPort: (int) 80,
        	            	@@ -8,3 +8,3 @@
        	            	  (api.PortPublisher) {
        	            	-  URL: (string) "",
        	            	+  URL: (string) (len=10) "invalid IP",
        	            	   TargetPort: (int) 443,
        	            	@@ -14,3 +14,3 @@
        	            	  (api.PortPublisher) {
        	            	-  URL: (string) "",
        	            	+  URL: (string) (len=10) "invalid IP",
        	            	   TargetPort: (int) 8080,
        	Test:       	TestPs/json
    --- FAIL: TestPs/json (0.12s)
```

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

Fix URL being set to "Invalid IP"

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>